In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("Company_Data.csv")
df

,Sales,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
0,9.50,138,73,11,276,120,Bad,42,17,Yes,Yes
1,11.22,111,48,16,260,83,Good,65,10,Yes,Yes
2,10.06,113,35,10,269,80,Medium,59,12,Yes,Yes
3,7.40,117,100,4,466,97,Medium,55,14,Yes,Yes
4,4.15,141,64,3,340,128,Bad,38,13,Yes,No
...,...,...,...,...,...,...,...,...,...,...,...
395,12.57,138,108,17,203,128,Good,33,14,Yes,Yes
396,6.14,139,23,3,37,120,Medium,55,11,No,Yes
397,7.41,162,26,12,368,159,Medium,40,18,Yes,Yes
398,5.94,100,79,7,284,95,Bad,50,12,Yes,Yes
399,9.71,134,37,0,27,120,Good,49,16,Yes,Yes

In [69]:
df.isna().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [38]:
y = df["Sales"]

In [39]:
x = df.iloc[:,1:]

In [24]:
from sklearn.model_selection import train_test_split

In [40]:
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.2,random_state=42)

In [43]:
x_train

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
212,145,69,19,501,105,Medium,45,11,Yes,Yes
295,118,35,14,502,137,Medium,79,10,No,Yes
364,122,21,16,488,131,Good,30,14,Yes,Yes
251,139,111,5,310,132,Bad,62,13,Yes,Yes
390,108,75,9,61,111,Medium,67,12,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...
71,148,51,16,148,150,Medium,58,17,No,Yes
106,102,33,0,217,139,Medium,70,18,No,No
270,119,26,0,284,89,Good,26,10,Yes,No
348,132,102,20,459,107,Good,49,11,Yes,Yes
102,113,22,0,57,97,Medium,65,16,No,No

In [48]:
# cat_cols = []
# con_cols = []
# for col in x_train.columns:
cat_cols = [cat for cat in x_train.columns if x_train[cat].dtype == "object"]
con_cols = [con for con in x_train.columns if x_train[con].dtype != "object"]

In [55]:
from sklearn.preprocessing import OneHotEncoder
x_check = x_train
x_check_y = x_test

In [68]:
x_check

,CompPrice,Income,Advertising,Population,Price,ShelveLoc,Age,Education,Urban,US
212,145,69,19,501,105,Medium,45,11,Yes,Yes
295,118,35,14,502,137,Medium,79,10,No,Yes
364,122,21,16,488,131,Good,30,14,Yes,Yes
251,139,111,5,310,132,Bad,62,13,Yes,Yes
390,108,75,9,61,111,Medium,67,12,Yes,Yes
...,...,...,...,...,...,...,...,...,...,...
71,148,51,16,148,150,Medium,58,17,No,Yes
106,102,33,0,217,139,Medium,70,18,No,No
270,119,26,0,284,89,Good,26,10,Yes,No
348,132,102,20,459,107,Good,49,11,Yes,Yes
102,113,22,0,57,97,Medium,65,16,No,No

In [72]:
cat_cols
oe = OneHotEncoder(handle_unknown="ignore")
oe_train = pd.DataFrame(oe.fit_transform(x_check[cat_cols]).toarray(),index=x_check[cat_cols].index)
oe_test = pd.DataFrame(oe.transform(x_check_y[cat_cols]).toarray(), index=x_check_y[cat_cols].index)
# x_check[cat_cols]  = oe.fit_transform(x_check[cat_cols])
# x_check_y[cat_cols] = oe.transform(x_check_y[cat_cols])

In [76]:
oe_train

       0    1    2    3    4    5    6
212  0.0  0.0  1.0  0.0  1.0  0.0  1.0
295  0.0  0.0  1.0  1.0  0.0  0.0  1.0
364  0.0  1.0  0.0  0.0  1.0  0.0  1.0
251  1.0  0.0  0.0  0.0  1.0  0.0  1.0
390  0.0  0.0  1.0  0.0  1.0  0.0  1.0
..   ...  ...  ...  ...  ...  ...  ...
71   0.0  0.0  1.0  1.0  0.0  0.0  1.0
106  0.0  0.0  1.0  1.0  0.0  1.0  0.0
270  0.0  1.0  0.0  0.0  1.0  1.0  0.0
348  0.0  1.0  0.0  0.0  1.0  0.0  1.0
102  0.0  0.0  1.0  1.0  0.0  1.0  0.0

[80 rows x 7 columns]

In [61]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

In [78]:
con_cols
x_check[con_cols] = sc.fit_transform(x_check[con_cols])
x_check_y[con_cols] = sc.transform(x_check_y[con_cols])

In [85]:
oe_train

       0    1    2    3    4    5    6
212  0.0  0.0  1.0  0.0  1.0  0.0  1.0
295  0.0  0.0  1.0  1.0  0.0  0.0  1.0
364  0.0  1.0  0.0  0.0  1.0  0.0  1.0
251  1.0  0.0  0.0  0.0  1.0  0.0  1.0
390  0.0  0.0  1.0  0.0  1.0  0.0  1.0
..   ...  ...  ...  ...  ...  ...  ...
71   0.0  0.0  1.0  1.0  0.0  0.0  1.0
106  0.0  0.0  1.0  1.0  0.0  1.0  0.0
270  0.0  1.0  0.0  0.0  1.0  1.0  0.0
348  0.0  1.0  0.0  0.0  1.0  0.0  1.0
102  0.0  0.0  1.0  1.0  0.0  1.0  0.0

[80 rows x 7 columns]

In [88]:
train_final = pd.concat([x_check[con_cols],oe_train],axis=1)

In [91]:
# test_final = 
test_final = pd.concat([x_check_y[con_cols],oe_test],axis=1)

In [110]:
# train_final 
y_train

212    12.04
295     4.21
364    10.50
251     3.72
390     5.47
       ...
71      6.50
106     0.16
270    11.99
348    12.57
102     5.30
Name: Sales, Length: 80, dtype: float64

In [122]:
from sklearn.ensemble import RandomForestRegressor
rr = RandomForestRegressor(random_state=42)
# train_final.columns = train_final.columns.astype(str)
rr.fit(train_final,y_train)

RandomForestRegressor(random_state=42)

In [115]:
x = [x for x in range(10)]

In [118]:
x

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [142]:
paramGrid = {"criterion": ["squared_error", "absolute_error","friedman_mse", "poisson"],
             "max_depth":[x for x in range(3,10)],
             "min_samples_split": [ sp for sp in range(2,6)],
             "n_jobs": [-1]}

In [143]:
from sklearn.model_selection import GridSearchCV
gv = GridSearchCV(estimator=rr, param_grid=paramGrid)
gv.fit(train_final,y_train)

GridSearchCV(estimator=RandomForestRegressor(random_state=42),
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_depth': [3, 4, 5, 6, 7, 8, 9],
                         'min_samples_split': [2, 3, 4, 5], 'n_jobs': [-1]})

In [145]:
gv.best_params_

{'criterion': 'poisson', 'max_depth': 7, 'min_samples_split': 3, 'n_jobs': -1}

In [137]:
gv.best_params_

{'criterion': 'poisson', 'max_depth': 7, 'min_samples_split': 3}

In [144]:
gv.best_score_

0.5372230951712773

In [138]:
gv.best_score_

0.5372230951712772