In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import numpy as np

In [3]:
df = pd.read_csv("50_Startups.csv")
df

    R&D Spend  Administration  Marketing Spend       State     Profit
0   165349.20       136897.80        471784.10    New York  192261.83
1   162597.70       151377.59        443898.53  California  191792.06
2   153441.51       101145.55        407934.54     Florida  191050.39
3   144372.41       118671.85        383199.62    New York  182901.99
4   142107.34        91391.77        366168.42     Florida  166187.94
5   131876.90        99814.71        362861.36    New York  156991.12
6   134615.46       147198.87        127716.82  California  156122.51
7   130298.13       145530.06        323876.68     Florida  155752.60
8   120542.52       148718.95        311613.29    New York  152211.77
9   123334.88       108679.17        304981.62  California  149759.96
10  101913.08       110594.11        229160.95     Florida  146121.95
11  100671.96        91790.61        249744.55  California  144259.40
12   93863.75       127320.38        249839.44     Florida  141585.52
13   91992.39       135495.07        252664.93  California  134307.35
14  119943.24       156547.42        256512.92     Florida  132602.65
15  114523.61       122616.84        261776.23    New York  129917.04
16   78013.11       121597.55        264346.06  California  126992.93
17   94657.16       145077.58        282574.31    New York  125370.37
18   91749.16       114175.79        294919.57     Florida  124266.90
19   86419.70       153514.11             0.00    New York  122776.86
20   76253.86       113867.30        298664.47  California  118474.03
21   78389.47       153773.43        299737.29    New York  111313.02
22   73994.56       122782.75        303319.26     Florida  110352.25
23   67532.53       105751.03        304768.73     Florida  108733.99
24   77044.01        99281.34        140574.81    New York  108552.04
25   64664.71       139553.16        137962.62  California  107404.34
26   75328.87       144135.98        134050.07     Florida  105733.54
27   72107.60       127864.55        353183.81    New York  105008.31
28   66051.52       182645.56        118148.20     Florida  103282.38
29   65605.48       153032.06        107138.38    New York  101004.64
30   61994.48       115641.28         91131.24     Florida   99937.59
31   61136.38       152701.92         88218.23    New York   97483.56
32   63408.86       129219.61         46085.25  California   97427.84
33   55493.95       103057.49        214634.81     Florida   96778.92
34   46426.07       157693.92        210797.67  California   96712.80
35   46014.02        85047.44        205517.64    New York   96479.51
36   28663.76       127056.21        201126.82     Florida   90708.19
37   44069.95        51283.14        197029.42  California   89949.14
38   20229.59        65947.93        185265.10    New York   81229.06
39   38558.51        82982.09        174999.30  California   81005.76
40   28754.33       118546.05        172795.67  California   78239.91
41   27892.92        84710.77        164470.71     Florida   77798.83
42   23640.93        96189.63        148001.11  California   71498.49
43   15505.73       127382.30         35534.17    New York   69758.98
44   22177.74       154806.14         28334.72  California   65200.33
45    1000.23       124153.04          1903.93    New York   64926.08
46    1315.46       115816.21        297114.46     Florida   49490.75
47       0.00       135426.92             0.00  California   42559.73
48     542.05        51743.15             0.00    New York   35673.41
49       0.00       116983.80         45173.06  California   14681.40

In [4]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1:]

In [5]:
y

       Profit
0   192261.83
1   191792.06
2   191050.39
3   182901.99
4   166187.94
5   156991.12
6   156122.51
7   155752.60
8   152211.77
9   149759.96
10  146121.95
11  144259.40
12  141585.52
13  134307.35
14  132602.65
15  129917.04
16  126992.93
17  125370.37
18  124266.90
19  122776.86
20  118474.03
21  111313.02
22  110352.25
23  108733.99
24  108552.04
25  107404.34
26  105733.54
27  105008.31
28  103282.38
29  101004.64
30   99937.59
31   97483.56
32   97427.84
33   96778.92
34   96712.80
35   96479.51
36   90708.19
37   89949.14
38   81229.06
39   81005.76
40   78239.91
41   77798.83
42   71498.49
43   69758.98
44   65200.33
45   64926.08
46   49490.75
47   42559.73
48   35673.41
49   14681.40

In [6]:
from sklearn.preprocessing import StandardScaler

In [7]:
x = pd.get_dummies(x).astype(int)

In [8]:
sc = StandardScaler()
new_df = sc.fit_transform(x)

In [9]:
x

,R&D Spend,Administration,Marketing Spend,State_California,State_Florida,State_New York
0,165349,136897,471784,0,0,1
1,162597,151377,443898,1,0,0
2,153441,101145,407934,0,1,0
3,144372,118671,383199,0,0,1
4,142107,91391,366168,0,1,0
5,131876,99814,362861,0,0,1
6,134615,147198,127716,1,0,0
7,130298,145530,323876,0,1,0
8,120542,148718,311613,0,0,1
9,123334,108679,304981,1,0,0
10,101913,110594,229160,0,1,0
11,100671,91790,249744,1,0,0
12,93863,127320,249839,0,1,0
13,91992,135495,252664,1,0,0
14,119943,156547,256512,0,1,0
15,114523,122616,261776,0,0,1
16,78013,121597,264346,1,0,0
17,94657,145077,282574,0,0,1
18,91749,114175,294919,0,1,0
19,86419,153514,0,0,0,1
20,76253,113867,298664,1,0,0
21,78389,153773,299737,0,0,1
22,73994,122782,303319,0,1,0
23,67532,105751,304768,0,1,0
24,77044,99281,140574,0,0,1
25,64664,139553,137962,1,0,0
26,75328,144135,134050,0,1,0
27,72107,127864,353183,0,0,1
28,66051,182645,118148,0,1,0
29,65605,153032,107138,0,0,1
30,61994,115641,91131,0,1,0
31,61136,152701,88218,0,0,1
32,63408,129219,46085,1,0,0
33,55493,103057,214634,0,1,0
34,46426,157693,210797,1,0,0
35,46014,85047,205517,0,0,1
36,28663,127056,201126,0,1,0
37,44069,51283,197029,1,0,0
38,20229,65947,185265,0,0,1
39,38558,82982,174999,1,0,0
40,28754,118546,172795,1,0,0
41,27892,84710,164470,0,1,0
42,23640,96189,148001,1,0,0
43,15505,127382,35534,0,0,1
44,22177,154806,28334,1,0,0
45,1000,124153,1903,0,0,1
46,1315,115816,297114,0,1,0
47,0,135426,0,1,0,0
48,542,51743,0,0,0,1
49,0,116983,45173,1,0,0

In [10]:
# x
new_df

array([[ 2.01641858e+00,  5.60742020e-01,  2.15394719e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [ 1.95585640e+00,  1.08280387e+00,  1.92360082e+00,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [ 1.75436392e+00, -7.28260419e-01,  1.62652786e+00,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [ 1.55478602e+00, -9.63780980e-02,  1.42220965e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [ 1.50494106e+00, -1.07993109e+00,  1.28152870e+00,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [ 1.27979148e+00, -7.76248286e-01,  1.25421193e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [ 1.34006757e+00,  9.32134225e-01, -6.88153288e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [ 1.24506506e+00,  8.71996161e-01,  9.32184639e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [ 1.03036862e+00,  9.86936297e-01,  8.30888737e-01,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [ 1.09181106e+00, -4.56629619e-01,  7.76106513e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [ 6.20407572e-01, -3.87586218e-01,  1.49803281e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [ 5.93075368e-01, -1.06554554e+00,  3.19833032e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [ 4.43254400e-01,  2.15452907e-01,  3.20617759e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [ 4.02080042e-01,  5.10194318e-01,  3.43953070e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [ 1.01718666e+00,  1.26920303e+00,  3.75738655e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [ 8.97910863e-01,  4.58549133e-02,  4.19220807e-01,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [ 9.44497085e-02,  9.11589216e-03,  4.40449745e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [ 4.60727645e-01,  8.55663701e-01,  5.91018259e-01,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [ 3.96732437e-01, -2.58476861e-01,  6.92991504e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [ 2.79437231e-01,  1.15985126e+00, -1.74312412e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [ 5.57180834e-02, -2.69581491e-01,  7.23926279e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [ 1.02724192e-01,  1.16918924e+00,  7.32789567e-01,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [ 6.00516241e-03,  5.18398765e-02,  7.62377916e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [-1.36201520e-01, -5.62195717e-01,  7.74347072e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [ 7.31253081e-02, -7.95465066e-01, -5.81942516e-01,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-1.99316464e-01,  6.56501431e-01, -6.03518386e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [ 3.53619737e-02,  8.21700837e-01, -6.35832629e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [-3.55213015e-02,  2.35066280e-01,  1.17426887e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-1.68793302e-01,  2.21014019e+00, -7.67187716e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [-1.78608248e-01,  1.14247323e+00, -8.58133477e-01,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-2.58074099e-01, -2.05621704e-01, -9.90355893e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [-2.76955767e-01,  1.13053936e+00, -1.01441811e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-2.26956760e-01,  2.83919444e-01, -1.36244879e+00,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [-4.01139039e-01, -6.59325180e-01,  2.98143500e-02,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [-6.00672928e-01,  1.31052090e+00, -1.88037177e-03,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [-6.09739650e-01, -1.30865763e+00, -4.54946879e-02,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-9.91576256e-01,  2.05934652e-01, -8.17656088e-02,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [-6.52542497e-01, -2.52598473e+00, -1.15608005e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [-1.17717996e+00, -1.99728894e+00, -2.12782023e-01,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-7.73820898e-01, -1.38310913e+00, -2.97582131e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [-9.89573655e-01, -1.00884847e-01, -3.15787804e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [-1.00854335e+00, -1.32080783e+00, -3.84554694e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [-1.10211543e+00, -9.06944019e-01, -5.20593363e-01,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [-1.28113917e+00,  2.17688255e-01, -1.44960308e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-1.13431110e+00,  1.20643302e+00, -1.50907715e+00,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [-1.60034497e+00,  1.01269904e-01, -1.72740480e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-1.59341289e+00, -1.99312254e-01,  7.11122834e-01,
        -7.17740563e-01,  1.45773797e+00, -7.17740563e-01],
       [-1.62235158e+00,  5.07706593e-01, -1.74312412e+00,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01],
       [-1.61042400e+00, -2.50939989e+00, -1.74312412e+00,
        -7.17740563e-01, -6.85994341e-01,  1.39326109e+00],
       [-1.62235158e+00, -1.57237242e-01, -1.36998217e+00,
         1.39326109e+00, -6.85994341e-01, -7.17740563e-01]])

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2, random_state=42)

In [12]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [13]:
y_pred = lr.predict(x_test)

In [14]:
comp = pd.DataFrame({"predicted":np.array(y_pred).reshape(-1),"actual":np.array(y_test).reshape(-1)})
comp

       predicted     actual
0  126362.932522  134307.35
1   84608.525799   81005.76
2   99677.450073   99937.59
3   46357.547098   64926.08
4  128750.693227  125370.37
5   50912.796508   35673.41
6  109741.008510  105733.54
7  100643.019252  107404.34
8   97598.947611   97427.84
9  113097.039752  122776.86

In [ ]:
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)